language: node_js
node_js:
    - '7'
    - '8'
    - '9'
    - '10'
    - '11'
    - '12'

jobs:
    include:
        - stage: npm release
          if: tag IS present
          node_js: 12
          deploy:
              provider: npm
              email: rogier+npm@konfirm.eu
              on:
                  branch: master
                  tags: true
              api_key:
                  secure: OBz7XzLs50IGZSHh/6Oklz/MFxRAjFrNDKU9yxJWQc17RPx9uAoSi0jwrmKV7zEfg+HLOVJU3dQFer4SXpTweuJjT63NGv8T3kG3UlKG67gGQPm4YydBJid3GKhoAtr3A7pyjO29Ijexm98WLRkMzTBy74euRJHF2sH5//++A35gBlnmXrHNENukDM1Oi6+x1fZUjwWZK0Ji5Gmcuw8ru0NVYm6djFaH7d3EUHQj7HlA71xZiyaLlq+QeqUSGXobxyP+Vxy15eTtF1PCfuK1OPSPWuBeuKVZO8Kmba8jobR4XFdVh+fpAUZz9yGAhYiiH21LtbY4uByV9cgkCspK0MNARbdSwplgvWiNToMe7610TAYyJmGaam0PhCRvvgE4sZ+p/klVgM5Az7i9TShpMlEnj594c+LXuanqF60Mal3s6WRunDgZpkm1UPKwN2pYsj9UlJ750n3u8Ty3N3pn9rWfihmbCfYTRctn6gbf5uG7q8BFvhIubmIsqSVFd350CfsSYHIy6Ux5TgDnt+kt/4706G9YGRRFwzFBxGQhptp9ATDbBZxtmzkYg0jik0ZoPQ+bkMghi6CnF6BcW/6hXvwsHtNdMFIby8DSVyxt0kUYFINCk4dJYR2nGH9A6VjCSUM6jvcbuKljaegLyfMg+z2ejUCW/G06GaaEpEdxs3U=

notifications:
    slack:
        secure: L+EVBsEla3wh5uC5RTrGQkmGyBZE7sYpc91jj/cPREKWhxCcTRlAVuVv+UJO+S2y2r3j+4FZy7nr2hPjCfrk8XtbCF0C9zaejj1hMTR70k1YGaK3afhkz7nzp/Hg6fc0FUd9ltESFQsOaqgR3N0cC/Td3N6lanuZf0khyAdXl6c4HwCCdhAcImAPo02z+f325fePhAUoxyQPkTkzaENTPr1CHY260y1Ve9RjtEgiiDwkXABK9XWoaTDuOmgxXZFvqtxsimnLxMnVjpfzdLZHNLe/tQiKTHa7/+yLK4NrVbrys6UNwRb3G5EDFZ0DRBm9dBprbz9VWCInhy56f5bfTsRxYulrL03F5oYHcLFSTiCxRmEsjxh6ihMLLFX9SxpsSH1CRHJDQe1PDDQpk9ilovPLa84ELapIKs2FisQAtpjd5ZCAfpCYCUoH8SbHi6m1RCjApUANKMR362+jtvsLCFWY+0UVYueJAjOXovb/C0ceK+/YJG5qUafSWvQcnh2LwFIFBwj3gz0uep/kNl9bcw0UWsaXu627VT+jfPwzwySBsyzWElsxMD/0Y17NlylAQklCMrezOOnTeJSWnGFlwQLk9+13+0BUNt9+xpVc6Jraim9fLNoHz6ssUlr1M+gX1kAQpPYGNCbhQP94BBRJdC6YADhboQDnUpwQld0WP84=
